version: '3'
services:
  atlas-api:
    image: node:18
    container_name: mongo_search_atlas_api
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules
      - ./tsconfig.json:/app/tsconfig.json
      - ./package.json:/app/package.json
    working_dir: /app
    ports:
      - 3001:3001
    command: npx ts-node src/server.ts
    env_file: .env